### ISSUE TITLE
Large Memory Unit (4GB) Error

### ISSUE THREAD

**Issue by GoTeamScotch** [Ryzee119/XMU_Dumper#1]
I have an upgraded memory unit that causes XMU_Dumper to error out due to its large capacity. This XMU has been [upgraded to 4GB](https://imgur.com/a/FVjKFGS). When attempting to dump it, XMU_Dumper errors-out with the following message:

![20220227_xmu](https://user-images.githubusercontent.com/11036843/155907518-71231dd7-57e5-4e33-ba20-11fb899646cf.jpg)
I assume that's in bytes, so it's checking to make sure the card isn't larger than 8MB.

This is undoubtedly an edge case, but I should mention that I also have a 3rd-party XMU that's 16MB in size (though I can't for the life of me find it), so this could potentially pop-up again in the future with other users. And since regular USB flash drives can be formatted to use as XMU's, those users would encounter this error as well.

If dumping a large (>8MB) XMU's isn't a feature worth adding, then perhaps capacity could be checked and a message displayed to the user if it exceeds the supported capacity.

Also, my specific XMU I'm using has a capacity of 4,003,528,704 bytes, which is below FATX's 4GB file size limit of 4,294,967,296 bytes.

_Note: My other stock 8MB MU was dumped successfully._

**Comment by Ryzee119** [comment]
The capacity is limited to 64mb just arbitrary. You can increase it  at the line shown in the error message.
64×1024=64mb
 If you want 4gb make it 4×1024×1024.
This will take along time to dump

**Comment by GoTeamScotch** [comment]
Oh ok. Then it was intentional. Guess I should have checked the code first.

Well I should build a version for myself then, since I'm pretty sure I'm the only one who would want such a thing.

I'll mark this as closed. Thx
